name: Create Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set the release name
        run: echo ::set-env name=RELEASE_NAME::${{ github.event.repository.name }}-${GITHUB_REF##*/}
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Create Release
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ env.RELEASE_NAME }}.zip
          directory: ozarkpack

      - name: List files
        run: ls -lr
        shell: bash

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ozarkpack/${{ env.RELEASE_NAME }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
